### ISSUE TITLE
Assertion Error in get_pruned_dict

### ISSUE THREAD

**Issue by zmertens** [rachelss/SISRS#13]
I've come across this error several times on my machine and on Hines. I'm using the command:

`bin/sisrs sites -g 11223441 -m 4 -t 0.99 -f /path/to/SISRS_test_data > sisrs_sites_out.txt`

This was with velvet/bowtie2.

```py
AssertionError: bases are being counted incorrectly: D should have 0 bases, but it is being converted to D
Traceback (most recent call last):
	File "/home/zach/repo/SISRS/libexec/sisrs/get_pruned_dict.py", line 93, in <module>
		allbases=getallbases(path) #dictionary of combined pileups - locus/pos:bases(as list)
	File "/home/zach/repo/SISRS/libexec/sisrs/get_pruned_dist.py", line 38, in getallbases
		bases + ' should have '+str(num)+' bases, but it is being converted to '+"".join(bases2)
```

**Comment by anderspitman** [comment]
I was not get the error using Arch with:

* Linux kernel 4.12.8-2
* velvet 1.2.10
* bowtie 2.3.2

Any other ideas on what might be causing it on your machine?

**Comment by anderspitman** [comment]
Oh wait it's actually not done yet. Looking at the wrong window. I'll update when it finishes.

**Comment by anderspitman** [comment]
Ok can confirm it didn't crash

**Comment by zmertens** [comment]
I haven't had any issues from the Docker container, but when I started using Manjaro Linux I encountered the error (I had previously been using Ubuntu).

**Comment by anderspitman** [comment]
I ran it both in the Docker container and on my Arch install directly.

**Comment by rachelss** [comment]
Runs ok on CentOS as far as I know. I assumed python was portable among OS.
