### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by kleigeb** [rachelss/SISRS#59]
Getting the following error when trying to run SISRS with the test data provided:

```==== Done Identifying Fixed Sites Without Error ====
748768 total variable sites (alignment.nex)
Traceback (most recent call last):
  File "/software/SISRS-1.6.2/libexec/sisrs/get_alignment_Memory.py", line 243, in <module>
    numbi=alignment.numsnps()
  File "/software/SISRS-1.6.2/libexec/sisrs/get_alignment_Memory.py", line 40, in numsnps
    if c[1][1]==1:
IndexError: list index out of range
get_alignment.py failed
```

I ran the following command from the test data directory to produce the command:

`$ /software/SISRS-1.6.2/bin/sisrs sites -g 1745690 -p 24`

Let me know if there's any more info I can provide to help find a resolution. Thanks.

**Comment by BobLiterman** [comment]
To clarify so that I can try to replicate, you're using the test  data from here? 

https://github.com/rachelss/SISRS_test_data

**Comment by kleigeb** [comment]
Correct.

**Comment by BobLiterman** [comment]
Alright, dove into the code and found what could have been the offending line. I was able to replicate your error, and then remove it. Clone the new code from GitHub and give it a shot? 

Thanks for the heads up!

**Comment by kleigeb** [comment]
Thanks! I'll give it a shot tomorrow morning and get back to you.

**Comment by kleigeb** [comment]
Ran with the test data this morning and everything completed successfully!
Thanks for your lightning fast help!
